### ISSUE TITLE
求最大公约数的方法——辗转相除法

### ISSUE THREAD

**Issue by yeshiqing** [pageYe123/zerobasedJava#1]
分数约分问题
https://github.com/pageYe123/JavaMOOC_icourse/tree/master/src_objectOrientedJava/week1_class

```
//求两个数的最大公约数(greatest common divisor)
int gcd(int a,int b)
    {
        int r;
        while(b != 0)
        {
            r = a % b;
            a = b;
            b = r;
        }
        return a;
    }
```
#

**Comment by pageYe123** [comment]
分数约分问题

https://github.com/pageYe123/JavaMOOC_icourse/tree/master/src_objectOrientedJava/week1_class
